### ISSUE TITLE
JIRA XML import not working

### ISSUE THREAD

**Issue by fabfrodo** [StevenWeathers/thunderdome-planning-poker#141] opened 2020-11-12 15:01 UTC
I'll try to import jira issues from our self hosted jira instance. But the generated XML file could not be imported. There is no error message.

**Comment by StevenWeathers** [comment] 2020-11-12 15:02
I have confirmed it working with a self hosted instance and the cloud instance, however I have seen mention that some people have issues with self hosted instance XML before.  Will take this as a sign to expose error messaging to help explain what went wrong.

**Comment by fabfrodo** [comment] 2020-11-12 15:40
Is it important to export the issues in a specific way or should the standard xml export work?

**Comment by StevenWeathers** [comment] 2020-11-12 16:02
> Is it important to export the issues in a specific way or should the standard xml export work?

Should be fine using the standard xml export feature in Jira, but another individual mentioned they had xml issues because of that.

**Comment by tnonnenm** [comment] 2020-11-13 06:11
Please check if the XML is well formatted. I had some issues with our self-hosted Jira server producing invalid XML - there was a problem encoding the description (HTML) with the correct amount of '&' and ';'.

Afterwards the import worked fine.

**Comment by fabfrodo** [comment] 2020-11-16 14:55
I've created an issue named "Test-Story" and then exported it. Is the syntax ok?

`Jira https://[URL]/issues/?jql=project+%3D+[PROJECT]+AND+resolution+%3D+Unresolved+AND+text+%7E+%22%5C%22Test-Story%5C%22%22+ORDER+BY+priority+DESC%2C+updated+DESC An XML representation of a search request en-us 8.11.0 811001 13-07-2020 [[PROJECT]-684] Test-Story https://[URL]/browse/[PROJECT]-684 project name [PROJECT]-684 Test-Story Story Normal Backlog Unresolved Unassigned [NAME] Mon, 16 Nov 2020 15:46:49 +0100 Mon, 16 Nov 2020 15:46:49 +0100 0 1 Check Interval 3 Jahre Classification SXB DC To Do Development Domain Section NEW OE Brand 123-Reg Rank 2|o03a7o: Rank (Obsolete) 9223372036854775807 Remindercounter 0.0 Service Request for Internal IT ToDo (Kanban Board) 
 
 
 <div class="o-completion" style="padding-bottom: 3px;">
 <span class="aui-lozenge aui-lozenge-complete">
 -
 
 </span>
 </div>
 
 Update Intervall in minutes 30.0 Workers Council Approved N/A gitBranch`

**Comment by StevenWeathers** [comment] 2020-11-16 14:56
@fabfrodo that does not look like XML, how did you export it?

**Comment by fabfrodo** [comment] 2020-11-16 15:00
I've searched for issues and used the export function choosing XML as format.

**Comment by StevenWeathers** [comment] 2020-11-16 15:04
@fabfrodo Ok I'm guessing you pasted the XML into github but didn't properly escape it as code so its not showing us the actual structure.

XML Should look like

```xml
 <rss version="0.92">
    <channel>
        <title>Jira</title>
        <link>https://skynetsoftwr.atlassian.net/issues/?jql=key+in+%28THUN-1%2C+THUN-2%29</link>
        <description>An XML representation of a search request</description>
        <language>en-us</language>
        <issue start="0" end="2" total="2"/>
        <build-info>
            <version>1001.0.0-SNAPSHOT</version>
            <build-number>100148</build-number>
            <build-date>08-10-2020</build-date>
        </build-info>
        <item>
            <title>[THUN-2] Just another ticket</title>
            <link>https://skynetsoftwr.atlassian.net/browse/THUN-2</link>
            <project id="10000" key="THUN">Thunerdome</project>
            <description>&lt;p&gt;With a &lt;b&gt;description&lt;/b&gt;&lt;/p&gt;</description>
            <environment></environment>
            <key id="10001">THUN-2</key>
            <summary>Just another ticket</summary>
            <type id="10001" iconUrl="https://skynetsoftwr.atlassian.net/secure/viewavatar?size=medium&amp;avatarId=10315&amp;avatarType=issuetype">Story</type>
            <priority id="3" iconUrl="https://skynetsoftwr.atlassian.net/images/icons/priorities/medium.svg">Medium</priority>
            <status id="10000" iconUrl="https://skynetsoftwr.atlassian.net/" description="">To Do</status>
            <statusCategory id="2" key="new" colorName="blue-gray"/>
            <resolution id="-1">Unresolved</resolution>
            <assignee username="-1">Unassigned</assignee>
            <reporter username="ug:069c5e83-ef14-49cd-92dc-d11e61612919">Steven Weathers</reporter>
            <labels>
            </labels>
            <created>Sat, 10 Oct 2020 17:31:32 -0400</created>
            <updated>Sat, 10 Oct 2020 17:31:32 -0400</updated>
            <due></due>
            <votes>0</votes>
            <watches>1</watches>
            <attachments>
            </attachments>
            <subtasks>
            </subtasks>
            <customfields>
                <customfield id="customfield_10000" key="com.atlassian.jira.plugins.jira-development-integration-plugin:devsummarycf">
                    <customfieldname>Development</customfieldname>
                    <customfieldvalues>
                    </customfieldvalues>
                </customfield>
                <customfield id="customfield_10019" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                    <customfieldname>Rank</customfieldname>
                    <customfieldvalues>
                    <customfieldvalue>0\|i00007:</customfieldvalue>
                    </customfieldvalues>
                </customfield>
                <customfield id="customfield_10020" key="com.pyxis.greenhopper.jira:gh-sprint">
                    <customfieldname>Sprint</customfieldname>
                    <customfieldvalues>
                    </customfieldvalues>
                </customfield>
            </customfields>
        </item>
    </channel>
  </rss>
```

**Comment by fabfrodo** [comment] 2020-11-16 15:12
I've found the fault. Using Google Chrome the export looks as expected. Previously I've used Apple Safari. 🤦

**Comment by StevenWeathers** [comment] 2020-11-16 15:14
@fabfrodo Good find, likely Safari was showing the text output of the xml, need to view the page source to get the actual XML then.

**Comment by fabfrodo** [comment] 2020-11-17 12:22
Finally I've got it. With Firefox on my Mac I'm able to generate a valid xml file from an issue search. This xml file seems to have the expected format to enable thunderdome to import the issues.

**Comment by sztrzask** [comment] 2020-11-24 08:55
I have the same issue - cannot load XML file on https://thunderdome.dev/. I'll try to set it up locally and debug it during weekend,

**Comment by tnonnenm** [comment] 2020-11-24 10:17
> And the issue was having & in XML document

This sounds more like a bug in Jira XML exporter

**Comment by kotlas92** [comment] 2020-11-27 08:51
In my case, everything works fine via Firefox (my version is 85.0a1 (2020-11-25) (64-bit), but my colleagues who use the stable version said the same) and doesn't work via the latest stable Chrome

**Comment by ShuzZzle** [comment] 2020-12-03 12:21
> I have the same issue - cannot load XML file on https://thunderdome.dev/. I'll try to set it up locally and debug it during weekend,
> 
> Edit:
> 
> And the issue was having & in XML document

So the & was not escaped properly? Ouch.

**Comment by lebg2** [comment] 2020-12-24 09:26
no problem using firefox (just right-lick on the XML export option on jira instead of left-clicking to open it, then save as)

**Comment by StevenWeathers** [comment] 2021-03-02 19:23
Closing this as xml generated from Jira isn't in our control, if it's invalid it won't be imported.

**Closed by StevenWeathers** 2021-03-02 19:23 UTC
Labels: bug
