### ISSUE TITLE
pq: relation "warriorsvote" already exists

### ISSUE THREAD

**Issue by ShuzZzle** [StevenWeathers/thunderdome-planning-poker#131] opened 2020-11-09 08:19 UTC
Hey,

Our Pod had to restart and is now getting:
```
2020/11/09 08:15:11 exec: "go": executable file not found in $PATH:
2020/11/09 08:15:11 Thunderdome version 1.1.6
2020/11/09 08:15:11 pq: relation "warriorsvote" already exists
```

Running thunderdome 1.1.6. Any Ideas?

I briefly checked the schema.sql but it seems that everything should be dropped if it exists

**Comment by StevenWeathers** [comment] 2020-11-09 13:41
There is no "warriorsvote" relation, so not sure what that is.  Did you have any customizations before?

**Comment by StevenWeathers** [comment] 2020-11-09 13:46
Ok never mind found the "warriorsvote" its the "WarriorsVote" type in the schema.
Apparently because all unquoted identifiers are folded to lower case automatically in PostgreSQL.

However I have not seen that error, has your postgres db version changed?  There is a drop statement for the type so unsure why it would have any issues.

**Comment by ShuzZzle** [comment] 2020-11-09 15:43
> However I have not seen that error, has your postgres db version changed? There is a drop statement for the type so unsure why it would have any issues.

yeah that's the part i didn't understand as well. Postgresql version was steady at version 12.4. But how is a PSQL type a relation?

**Comment by StevenWeathers** [comment] 2020-11-09 15:45
> > However I have not seen that error, has your postgres db version changed? There is a drop statement for the type so unsure why it would have any issues.
> 
> yeah that's the part i didn't understand as well. Postgresql version was steady at version 12.4. But how is a PSQL type a relation?

Its just poor error messaging to be honest, essentially its throwing an error because the type already exists when its trying to create it but it should be dropped first anyway.
By chance are you running more than 1 instance of Thunderdome?  This would likely cause a race condition (and doesn't work well with web sockets anyway).

**Comment by ShuzZzle** [comment] 2020-11-09 15:51
> > > However I have not seen that error, has your postgres db version changed? There is a drop statement for the type so unsure why it would have any issues.
> > 
> > 
> > yeah that's the part i didn't understand as well. Postgresql version was steady at version 12.4. But how is a PSQL type a relation?
> 
> Its just poor error messaging to be honest, essentially its throwing an error because the type already exists when its trying to create it but it should be dropped first anyway.
> By chance are you running more than 1 instance of Thunderdome? This would likely cause a race condition (and doesn't work well with web sockets anyway).

nope just running one instance. I will continue to observe it and if it happens again i will let you know and hopefully be able to provide more information.


I wish i could be of further help

**Comment by StevenWeathers** [comment] 2020-11-09 19:25
No problem I will close this for now as I am unable to reproduce this error.

**Closed by StevenWeathers** 2020-11-09 19:25 UTC
