### ISSUE TITLE
[Poker] Switching to finished plans removes activation state

### ISSUE THREAD

**Issue by Kurisutian** [StevenWeathers/thunderdome-planning-poker#380] opened 2022-11-22 13:37 UTC
### Problem

When activating a plan to be voted on switching to the tab with already voted items will remove the "activate" state from the previously activated ticket. It still can be voted on but when switching back to the list of unvoted tickets it can be activated again resulting in all votes that have been made so far are removed and voting starts over. 

### Expectation

When changing between voted and unvoted tabs the already activated plan should remain active and should not switch back to the initial state where it can be re-activated and therefore votes will be reset.

### Steps to reproduce

- Create a battle
- Put some plans in there
- Activate Vote on a plan and finish voting
- Activate the next plan and have a vote (not finishing though)
- Switch to the list of finished plans
- Switch back to the list of plans to vote on
- Check if the current plan to vote on is still activated in the list

**Comment by StevenWeathers** [comment] 2022-12-08 03:40
I'm unable to reproduce the above issue following the steps listed.  Could you provide a video showing the behavior?

**Comment by StevenWeathers** [comment] 2023-06-21 02:09
Closing unable to reproduce, if you can provide further steps or browser details I can try and reproduce otherwise nothing I can fix.

**Closed by StevenWeathers** 2023-06-21 02:09 UTC
Labels: question
